name: augmentation_htr
channels:
  - conda-forge
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - alabaster=1.0.0=pyhd8ed1ab_1
  - annotated-types=0.7.0=pyhd8ed1ab_1
  - aom=3.9.1=h7bae524_0
  - app-model=0.2.8=pyhd8ed1ab_0
  - appdirs=1.4.4=pyhd8ed1ab_1
  - appnope=0.1.4=pyhd8ed1ab_1
  - asttokens=3.0.0=pyhd8ed1ab_1
  - attrs=25.3.0=pyh71513ae_0
  - babel=2.17.0=pyhd8ed1ab_0
  - blosc=1.21.6=h7dd00d9_1
  - brotli=1.1.0=h5505292_3
  - brotli-bin=1.1.0=h5505292_3
  - brotli-python=1.1.0=py313h928ef07_3
  - brunsli=0.1=h9f76cd9_0
  - bzip2=1.0.8=h99b78c6_7
  - c-ares=1.34.5=h5505292_0
  - c-blosc2=2.19.0=h9cbb436_0
  - ca-certificates=2025.7.14=hbd8a1cb_0
  - cachey=0.2.1=pyh9f0ad1d_0
  - cairo=1.18.4=h6a3b0d2_0
  - certifi=2025.7.14=pyhd8ed1ab_0
  - cffi=1.17.1=py313hc845a76_0
  - charls=2.4.2=h13dd4ca_0
  - charset-normalizer=3.4.2=pyhd8ed1ab_0
  - click=8.2.1=pyh707e725_0
  - cloudpickle=3.1.1=pyhd8ed1ab_0
  - colorama=0.4.6=pyhd8ed1ab_1
  - comm=0.2.2=pyhd8ed1ab_1
  - contourpy=1.3.2=py313h0ebd0e5_0
  - crc32c=2.7.1=py313h90d716c_1
  - cycler=0.12.1=pyhd8ed1ab_1
  - cyrus-sasl=2.1.28=ha1cbb27_0
  - cytoolz=1.0.1=py313h90d716c_0
  - dask-core=2025.5.1=pyhd8ed1ab_0
  - dav1d=1.2.1=hb547adb_0
  - dbus=1.16.2=hda038a8_0
  - debugpy=1.8.14=py313h928ef07_0
  - decorator=5.2.1=pyhd8ed1ab_0
  - deprecated=1.2.18=pyhd8ed1ab_0
  - docstring_parser=0.16=pyhd8ed1ab_0
  - docutils=0.21.2=pyhd8ed1ab_1
  - donfig=0.8.1.post1=pyhd8ed1ab_1
  - double-conversion=3.3.1=h286801f_0
  - exceptiongroup=1.3.0=pyhd8ed1ab_0
  - executing=2.2.0=pyhd8ed1ab_0
  - ffmpeg=7.1.1=gpl_h20db955_106
  - flexcache=0.3=pyhd8ed1ab_1
  - flexparser=0.4=pyhd8ed1ab_1
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=h77eed37_3
  - fontconfig=2.15.0=h1383a14_1
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=0
  - fonttools=4.58.5=py313ha9b7d5b_0
  - freetype=2.13.3=hce30654_1
  - freetype-py=2.5.1=pyhd8ed1ab_1
  - fribidi=1.0.10=h27ca646_0
  - fsspec=2025.5.1=pyhd8ed1ab_0
  - gdk-pixbuf=2.42.12=h7ddc832_0
  - giflib=5.2.2=h93a5062_0
  - gmp=6.3.0=h7bae524_2
  - graphite2=1.3.14=h286801f_0
  - h2=4.2.0=pyhd8ed1ab_0
  - harfbuzz=11.2.1=hab40de2_0
  - hdf5=1.14.6=nompi_ha698983_101
  - heapdict=1.0.1=pyhd8ed1ab_2
  - hpack=4.1.0=pyhd8ed1ab_0
  - hsluv=5.0.4=pyhd8ed1ab_2
  - hyperframe=6.1.0=pyhd8ed1ab_0
  - icu=75.1=hfee45f7_0
  - idna=3.10=pyhd8ed1ab_1
  - imagecodecs=2025.3.30=py313h3735ba5_2
  - imageio=2.37.0=pyhfb79c49_0
  - imagesize=1.4.1=pyhd8ed1ab_0
  - imath=3.1.12=h025cafa_0
  - importlib-metadata=8.7.0=pyhe01879c_1
  - importlib_resources=6.5.2=pyhd8ed1ab_0
  - in-n-out=0.2.1=pyhd8ed1ab_1
  - ipykernel=6.29.5=pyh57ce528_0
  - ipython=9.4.0=pyhfa0c392_0
  - ipython_pygments_lexers=1.1.1=pyhd8ed1ab_0
  - jasper=4.2.5=h743e416_0
  - jedi=0.19.2=pyhd8ed1ab_1
  - jinja2=3.1.6=pyhd8ed1ab_0
  - jsonschema=4.24.0=pyhd8ed1ab_0
  - jsonschema-specifications=2025.4.1=pyh29332c3_0
  - jupyter_client=8.6.3=pyhd8ed1ab_1
  - jupyter_core=5.8.1=pyh31011fe_0
  - jxrlib=1.1=h93a5062_3
  - kiwisolver=1.4.8=py313h0ebd0e5_1
  - krb5=1.21.3=h237132a_0
  - lame=3.100=h1a8c8d9_1003
  - lazy-loader=0.4=pyhd8ed1ab_2
  - lazy_loader=0.4=pyhd8ed1ab_2
  - lcms2=2.17=h7eeda09_0
  - lerc=4.0.0=hd64df32_1
  - libabseil=20250127.1=cxx17_h07bc746_0
  - libaec=1.1.4=h51d1e36_0
  - libasprintf=0.25.1=h493aca8_0
  - libass=0.17.3=h68e5b86_2
  - libavif16=1.3.0=hf1e31eb_0
  - libblas=3.9.0=32_h10e41b3_openblas
  - libbrotlicommon=1.1.0=h5505292_3
  - libbrotlidec=1.1.0=h5505292_3
  - libbrotlienc=1.1.0=h5505292_3
  - libcblas=3.9.0=32_hb3479ef_openblas
  - libclang-cpp18.1=18.1.8=default_hf90f093_10
  - libclang13=20.1.7=default_hee4fbb3_0
  - libcurl=8.14.1=h73640d1_0
  - libcxx=20.1.7=ha82da77_0
  - libdeflate=1.24=h5773f1b_0
  - libedit=3.1.20250104=pl5321hafb1f1b_0
  - libev=4.33=h93a5062_2
  - libexpat=2.7.0=h286801f_0
  - libffi=3.4.6=h1da3d7d_1
  - libfreetype=2.13.3=hce30654_1
  - libfreetype6=2.13.3=h1d14073_1
  - libgettextpo=0.25.1=h493aca8_0
  - libgfortran=5.0.0=14_2_0_h6c33f7e_103
  - libgfortran5=14.2.0=h6c33f7e_103
  - libglib=2.84.2=hbec27ea_0
  - libhwloc=2.11.2=default_hbce5d74_1001
  - libhwy=1.2.0=h9a9ea7e_0
  - libiconv=1.18=hfe07756_1
  - libintl=0.25.1=h493aca8_0
  - libjpeg-turbo=3.1.0=h5505292_0
  - libjxl=0.11.1=h72d67bc_2
  - liblapack=3.9.0=32_hc9a63f6_openblas
  - liblapacke=3.9.0=32_hbb7bcf8_openblas
  - libllvm18=18.1.8=hc4b4ae8_3
  - libllvm20=20.1.7=h598bca7_0
  - liblzma=5.8.1=h39f12f2_2
  - libmpdec=4.0.0=h5505292_0
  - libnghttp2=1.64.0=h6d7220d_0
  - libntlm=1.8=h5505292_0
  - libogg=1.3.5=h48c0fde_1
  - libopenblas=0.3.30=openmp_hf332438_0
  - libopencv=4.12.0=qt6_py313hb7231e8_600
  - libopenvino=2025.0.0=h3f17238_3
  - libopenvino-arm-cpu-plugin=2025.0.0=h3f17238_3
  - libopenvino-auto-batch-plugin=2025.0.0=h7f72211_3
  - libopenvino-auto-plugin=2025.0.0=h7f72211_3
  - libopenvino-hetero-plugin=2025.0.0=h718ad69_3
  - libopenvino-ir-frontend=2025.0.0=h718ad69_3
  - libopenvino-onnx-frontend=2025.0.0=h1ae5b81_3
  - libopenvino-paddle-frontend=2025.0.0=h1ae5b81_3
  - libopenvino-pytorch-frontend=2025.0.0=h286801f_3
  - libopenvino-tensorflow-frontend=2025.0.0=heb6e3e1_3
  - libopenvino-tensorflow-lite-frontend=2025.0.0=h286801f_3
  - libopus=1.5.2=h48c0fde_0
  - libpng=1.6.50=h3783ad8_0
  - libpq=17.5=h6896619_0
  - libprotobuf=5.29.3=hccd9074_1
  - librsvg=2.58.4=h266df6f_3
  - libsodium=1.0.20=h99b78c6_0
  - libsqlite=3.50.2=h6fb428d_0
  - libssh2=1.11.1=h1590b86_0
  - libtiff=4.7.0=h2f21f7c_5
  - libusb=1.0.29=hbc156a2_0
  - libvorbis=1.3.7=h9f76cd9_0
  - libvpx=1.14.1=h7bae524_0
  - libwebp-base=1.5.0=h2471fea_0
  - libxcb=1.17.0=hdb1d25a_0
  - libxml2=2.13.8=h52572c6_0
  - libxslt=1.1.39=h223e5b9_0
  - libzlib=1.3.1=h8359307_2
  - libzopfli=1.0.3=h9f76cd9_0
  - llvm-openmp=20.1.7=hdb05f8b_0
  - locket=1.0.0=pyhd8ed1ab_0
  - lxml=6.0.0=py313hbe1e15d_0
  - lz4-c=1.10.0=h286801f_1
  - magicgui=0.10.1=pyhd8ed1ab_0
  - markdown-it-py=3.0.0=pyhd8ed1ab_1
  - markupsafe=3.0.2=py313ha9b7d5b_1
  - matplotlib=3.10.3=py313h39782a4_0
  - matplotlib-base=3.10.3=py313haaf02c0_0
  - matplotlib-inline=0.1.7=pyhd8ed1ab_1
  - mdurl=0.1.2=pyhd8ed1ab_1
  - msgpack-python=1.1.1=py313h0ebd0e5_0
  - munkres=1.1.4=pyhd8ed1ab_1
  - napari=0.5.0=pyh9208f05_1
  - napari-console=0.1.3=pyh73487a3_0
  - napari-plugin-engine=0.2.0=pyha07c04f_3
  - napari-skimage=0.5.0=pyh73487a3_0
  - napari-svg=0.2.1=pyha07c04f_0
  - ncurses=6.5=h5e97a16_3
  - nest-asyncio=1.6.0=pyhd8ed1ab_1
  - networkx=3.5=pyhe01879c_0
  - npe2=0.7.8=pyhd8ed1ab_0
  - numcodecs=0.16.1=py313h668b085_0
  - numpy=2.3.1=py313h41a2e72_0
  - numpydoc=1.9.0=pyhe01879c_1
  - opencv=4.12.0=qt6_py313h4682daf_600
  - openexr=3.3.4=h37c74dd_0
  - openh264=2.6.0=hb5b2745_0
  - openjpeg=2.5.3=h8a3d83b_0
  - openldap=2.6.10=hbe55e7a_0
  - openssl=3.5.1=h81ee809_0
  - packaging=25.0=pyh29332c3_1
  - pandas=2.3.0=py313h668b085_0
  - pango=1.56.4=h875632e_0
  - parso=0.8.4=pyhd8ed1ab_1
  - partd=1.4.2=pyhd8ed1ab_0
  - pcre2=10.45=ha881caa_0
  - pexpect=4.9.0=pyhd8ed1ab_1
  - pickleshare=0.7.5=pyhd8ed1ab_1004
  - pillow=11.3.0=py313hb37fac4_0
  - pint=0.24.4=pyhd8ed1ab_1
  - pip=25.1.1=pyh145f28c_0
  - pixman=0.46.2=h2f9eb0b_0
  - pkgutil-resolve-name=1.3.10=pyhd8ed1ab_2
  - platformdirs=4.3.8=pyhe01879c_0
  - pooch=1.8.2=pyhd8ed1ab_1
  - prompt-toolkit=3.0.51=pyha770c72_0
  - psutil=7.0.0=py313h90d716c_0
  - psygnal=0.13.0=pyhd8ed1ab_0
  - pthread-stubs=0.4=hd74edd7_1002
  - ptyprocess=0.7.0=pyhd8ed1ab_1
  - pugixml=1.15=hd3d436d_0
  - pure_eval=0.2.3=pyhd8ed1ab_1
  - py-opencv=4.12.0=qt6_py313h6f5c724_600
  - pyconify=0.2.1=pyhd8ed1ab_0
  - pycparser=2.22=pyh29332c3_1
  - pydantic=2.11.7=pyh3cfb1c2_0
  - pydantic-compat=0.1.2=pyhd8ed1ab_0
  - pydantic-core=2.33.2=py313hf3ab51e_0
  - pygments=2.19.2=pyhd8ed1ab_0
  - pyopengl=3.1.9=pyhd8ed1ab_0
  - pyparsing=3.2.3=pyhd8ed1ab_1
  - pyproject_hooks=1.2.0=pyhd8ed1ab_1
  - pysocks=1.7.1=pyha55dd90_7
  - python=3.13.5=hf3f3da0_102_cp313
  - python-build=1.2.2.post1=pyhff2d567_1
  - python-dateutil=2.9.0.post0=pyhe01879c_2
  - python-tzdata=2025.2=pyhd8ed1ab_0
  - python_abi=3.13=7_cp313
  - pytz=2025.2=pyhd8ed1ab_0
  - pywavelets=1.8.0=py313h46657e6_0
  - pyyaml=6.0.2=py313ha9b7d5b_2
  - pyzmq=27.0.0=py313he6960b1_0
  - qhull=2020.2=h420ef59_5
  - qt6-main=6.9.1=h9cca212_1
  - qtconsole-base=5.6.1=pyha770c72_2
  - qtpy=2.4.3=pyhd8ed1ab_1
  - rav1e=0.7.1=h0716509_3
  - readline=8.2=h1d1bf99_2
  - referencing=0.36.2=pyh29332c3_0
  - requests=2.32.4=pyhd8ed1ab_0
  - rich=14.0.0=pyh29332c3_0
  - roman-numerals-py=3.1.0=pyhd8ed1ab_0
  - rpds-py=0.26.0=py313hf3ab51e_0
  - scikit-image=0.25.2=py313h668b085_1
  - scipy=1.16.0=py313h9a24e0a_0
  - sdl2=2.32.54=ha1acc90_0
  - sdl3=3.2.16=h92d3ae7_0
  - shellingham=1.5.4=pyhd8ed1ab_1
  - six=1.17.0=pyhd8ed1ab_0
  - snappy=1.2.1=h98b9ce2_1
  - snowballstemmer=3.0.1=pyhd8ed1ab_0
  - sphinx=8.2.3=pyhd8ed1ab_0
  - sphinxcontrib-applehelp=2.0.0=pyhd8ed1ab_1
  - sphinxcontrib-devhelp=2.0.0=pyhd8ed1ab_1
  - sphinxcontrib-htmlhelp=2.1.0=pyhd8ed1ab_1
  - sphinxcontrib-jsmath=1.0.1=pyhd8ed1ab_1
  - sphinxcontrib-qthelp=2.0.0=pyhd8ed1ab_1
  - sphinxcontrib-serializinghtml=1.1.10=pyhd8ed1ab_1
  - stack_data=0.6.3=pyhd8ed1ab_1
  - superqt=0.7.5=pyhb6d5dde_0
  - svt-av1=3.0.2=h8ab69cd_0
  - tbb=2022.1.0=h9541205_0
  - tifffile=2025.6.11=pyhd8ed1ab_0
  - tk=8.6.13=h892fb3f_2
  - tomli=2.2.1=pyhd8ed1ab_1
  - tomli-w=1.2.0=pyhd8ed1ab_0
  - toolz=1.0.0=pyhd8ed1ab_1
  - tornado=6.5.1=py313h90d716c_0
  - tqdm=4.67.1=pyhd8ed1ab_1
  - traitlets=5.14.3=pyhd8ed1ab_1
  - typer=0.16.0=pyh167b9f4_0
  - typer-slim=0.16.0=pyhe01879c_0
  - typer-slim-standard=0.16.0=hf964461_0
  - typing-extensions=4.14.1=h4440ef1_0
  - typing-inspection=0.4.1=pyhd8ed1ab_0
  - typing_extensions=4.14.1=pyhe01879c_0
  - tzdata=2025b=h78e105d_0
  - urllib3=2.5.0=pyhd8ed1ab_0
  - vispy=0.14.3=py313hf213cfb_1
  - wcwidth=0.2.13=pyhd8ed1ab_1
  - wrapt=1.17.2=py313h90d716c_0
  - x264=1!164.3095=h57fd34a_2
  - x265=3.5=hbc6ce65_3
  - xorg-libxau=1.0.12=h5505292_0
  - xorg-libxdmcp=1.1.5=hd74edd7_0
  - yaml=0.2.5=h3422bc3_2
  - zarr=3.0.10=pyhd8ed1ab_0
  - zeromq=4.3.5=hc1bb282_7
  - zfp=1.0.1=h1c5d8ea_2
  - zipp=3.23.0=pyhd8ed1ab_0
  - zlib-ng=2.2.4=h13dfb9a_0
  - zstandard=0.23.0=py313h90d716c_2
  - zstd=1.5.7=h6491c7d_2
